version: '3.3'

services:

  elasticsearch:
    image: comworkio/elasticsearch:7.13.2-arm
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/7.13/bootstrap-checks.html
      discovery.type: single-node
      # Force publishing on the 'ek' overlay.
      network.publish_host: _eth0_
    networks:
      - ek
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: comworkio/kibana:7.13.2-arm
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - ek
    deploy:
      mode: replicated
      replicas: 1

configs:

  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  kibana_config:
    file: ./kibana/config/kibana.yml

networks:
  ek:
    driver: overlay
